# Generated by Django 4.0.5 on 2022-06-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atYourService', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
