# Generated by Django 4.0.5 on 2022-06-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atYourService', '0003_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
