# Generated by Django 4.0.5 on 2022-06-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atYourService', '0005_alter_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Date_joined',
            new_name='DateJoined',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Name',
            new_name='UserName',
        ),
    ]
